public class Art
{
   public static void main(String[] args)
      {
      System.out.println("Alex Liang 9/21/18");
      System.out.println("\n");
      System.out.println("The Ant Colony");
      System.out.println("\n");
      System.out.println("        \\ /        \\ \\");
      System.out.println("  ___  _(\")        ('')_  ___");
      System.out.println(" (___)(_)             (_)(___)");
      System.out.println(" //|| ||               || ||\\\\");
      System.out.println("_________________________________");
      System.out.println("        \\ /        \\ \\");
      System.out.println("  ___  _(\")        ('')_  ___");
      System.out.println(" (___)(_)             (_)(___)");
      System.out.println(" //|| ||               || ||\\\\");
      System.out.println("_________________________________");
      System.out.println("        \\ /        \\ \\");
      System.out.println("  ___  _(\")        ('')_  ___");
      System.out.println(" (___)(_)             (_)(___)");
      System.out.println(" //|| ||               || ||\\\\");
      System.out.println("_________________________________");
      System.out.println("        \\ /        \\ \\");
      System.out.println("  ___  _(\")        ('')_  ___");
      System.out.println(" (___)(_)             (_)(___)");
      System.out.println(" //|| ||               || ||\\\\");
      System.out.println("_________________________________");
      System.out.println("        \\ /        \\ \\");
      System.out.println("  ___  _(\")        ('')_  ___");
      System.out.println(" (___)(_)             (_)(___)");
      System.out.println(" //|| ||               || ||\\\\");
      System.out.println("_________________________________");
      System.out.println("        \\ /        \\ \\");
      System.out.println("  ___  _(\")        ('')_  ___");
      System.out.println(" (___)(_)             (_)(___)");
      System.out.println(" //|| ||               || ||\\\\");
      System.out.println("_________________________________");
      System.out.println("        \\ /        \\ \\");
      System.out.println("  ___  _(\")        ('')_  ___");
      System.out.println(" (___)(_)             (_)(___)");
      System.out.println(" //|| ||               || ||\\\\");
      System.out.println("_________________________________");
      System.out.println("        \\ /        \\ \\");
      System.out.println("  ___  _(\")        ('')_  ___");
      System.out.println(" (___)(_)             (_)(___)");
      System.out.println(" //|| ||               || ||\\\\");
      System.out.println("_________________________________");
      System.out.println("        \\ /        \\ \\");
      System.out.println("  ___  _(\")        ('')_  ___");
      System.out.println(" (___)(_)             (_)(___)");
      System.out.println(" //|| ||               || ||\\\\");
      System.out.println("_________________________________");
      System.out.println("        \\ /        \\ \\");
      System.out.println("  ___  _(\")        ('')_  ___");
      System.out.println(" (___)(_)             (_)(___)");
      System.out.println(" //|| ||               || ||\\\\");
      System.out.println("_________________________________");
      System.out.println("        \\ /        \\ \\");
      System.out.println("  ___  _(\")        ('')_  ___");
      System.out.println(" (___)(_)             (_)(___)");
      System.out.println(" //|| ||               || ||\\\\");
      System.out.println("_________________________________");
      System.out.println("        \\ /        \\ \\");
      System.out.println("  ___  _(\")        ('')_  ___");
      System.out.println(" (___)(_)             (_)(___)");
      System.out.println(" //|| ||               || ||\\\\");
      System.out.println("_________________________________");
      System.out.println("        \\ /        \\ \\");
      System.out.println("  ___  _(\")        ('')_  ___");
      System.out.println(" (___)(_)             (_)(___)");
      System.out.println(" //|| ||               || ||\\\\");
      System.out.println("_________________________________");
      System.out.println("        \\ /        \\ \\");
      System.out.println("  ___  _(\")        ('')_  ___");
      System.out.println(" (___)(_)             (_)(___)");
      System.out.println(" //|| ||               || ||\\\\");
      System.out.println("_________________________________");
      System.out.println("        \\ /        \\ \\");
      System.out.println("  ___  _(\")        ('')_  ___");
      System.out.println(" (___)(_)             (_)(___)");
      System.out.println(" //|| ||               || ||\\\\");
      System.out.println("_________________________________");
      System.out.println("        \\ /        \\ \\");
      System.out.println("  ___  _(\")        ('')_  ___");
      System.out.println(" (___)(_)             (_)(___)");
      System.out.println(" //|| ||               || ||\\\\");
      System.out.println("_________________________________");
      System.out.println("        \\ /        \\ \\");
      System.out.println("  ___  _(\")        ('')_  ___");
      System.out.println(" (___)(_)             (_)(___)");
      System.out.println(" //|| ||               || ||\\\\");
      System.out.println("_________________________________");
      System.out.println("        \\ /        \\ \\");
      System.out.println("  ___  _(\")        ('')_  ___");
      System.out.println(" (___)(_)             (_)(___)");
      System.out.println(" //|| ||               || ||\\\\");
      System.out.println("_________________________________");
      System.out.println("        \\ /        \\ \\");
      System.out.println("  ___  _(\")        ('')_  ___");
      System.out.println(" (___)(_)             (_)(___)");
      System.out.println(" //|| ||               || ||\\\\");
      System.out.println("_________________________________");
      System.out.println("        \\ /        \\ \\");
      System.out.println("  ___  _(\")        ('')_  ___");
      System.out.println(" (___)(_)             (_)(___)");
      System.out.println(" //|| ||               || ||\\\\");
      System.out.println("_________________________________");
      System.out.println("        \\ /        \\ \\");
      System.out.println("  ___  _(\")        ('')_  ___");
      System.out.println(" (___)(_)             (_)(___)");
      System.out.println(" //|| ||               || ||\\\\");
      System.out.println("_________________________________");
      System.out.println("        \\ /        \\ \\");
      System.out.println("  ___  _(\")        ('')_  ___");
      System.out.println(" (___)(_)             (_)(___)");
      System.out.println(" //|| ||               || ||\\\\");
      System.out.println("_________________________________");
      System.out.println("        \\ /        \\ \\");
      System.out.println("  ___  _(\")        ('')_  ___");
      System.out.println(" (___)(_)             (_)(___)");
      System.out.println(" //|| ||               || ||\\\\");
      System.out.println("_________________________________");
      System.out.println("        \\ /        \\ \\");
      System.out.println("  ___  _(\")        ('')_  ___");
      System.out.println(" (___)(_)             (_)(___)");
      System.out.println(" //|| ||               || ||\\\\");
      System.out.println("_________________________________");
      System.out.println("\n");
      System.out.println("\n");
      System.out.println("Helpful Hints");
      System.out.println("\\ draws one backslash on the screen!");
      System.out.println("\" draws one double quote on the screen!");
      System.out.println("' draws one single quote on the screen!");
      System.out.println("Press any key to continue...");
      }
} 
     